INSERT INTO censustrips.gb_oa_2021
(
 id, oa_code, oa_code_11, change1121, lsoa_code, totpop, hhd, pop_dens, dwellings, hhdpop, commpop, male, female, age_0_2, age_3_4, age_5_7, age_8_9, age_10_14, age_15, age_16_17, age_18_19, age_20_24, age_25_29, age_30_34, age_35_39, age_40_44, age_45_49, age_50_54, age_55_59, age_60_64, age_65, age_66_69, age_70_74, age_75_79, age_80_84, age_85_pl, divorced, msnotapply, formciv, civil_os, civil_ss, married_os, married_ss, single, sep_civ, sepmarried, survciv, widowed, aabwbang, aabwchin, aabwindia, aabwoth, aabwpak, bbwcaafr, bbwcacar, bbwcaoth, mixedeth, othereth, whitetot, whitebr, cobafrica, cobanocoth, cobbriosea, cobeuother, cobeu14, cobeu2, cobeu8, cobnoneu, cobuk, cobmea, cobamca, rbuddhist, rchrist, rhindu, rjewish, rmuslim, noreligion, noanswer, otherrel, rsikh, badhealth, fairhealth, ghealth, vbadhealth, vghealth, eaemp, eaeself, eaunemp, eafutist, eiltsdis, eihfam, eioth, eiret, eistu, agricult, extractive, manufact, energysup, ind_dna, watersup, construct, retail, transport, accommfood, infocomms, finserv, propserv, proftech, administ, pubaddef, education, health, otherind, nssecdna, l123hmapro, l1011lstec, l12semrou, l13routine, l14nwltune, l15ftstu, l456lmapro, l7inter, l89seoacc, lq_appren, lq_na, lq_level1, lq_level2, lq_level3, lq_level4, lq_no, lq_other, edu_na, notstudent, student, multoth, multdepkid, pens1pers, other1pers, pensfamily, condepkid, conokid, codepkid, lpndepkid, lpdepkid, mandepkid, madepkid, manokid, singoth, at_mobile, at_detach, at_comm, at_flat, at_anyconv, at_othconv, at_semdet, at_terr, ten_rentfr, ten_ownout, ten_ownmort, ten_proth, ten_prllla, ten_so, ten_sroth, ten_srrent, cva_1, cva_2, cva_3pl, cva_no, pers1hhd, pers2hhd, pers3hhd, pers4hhd, pers5hhd, pers6plhhd, abhrp, c1hrp, c2hrp, dehrp, geom
)
SELECT id, oa_code, oa_code_11, change1121, lsoa_code, totpop, hhd, pop_dens, dwellings, hhdpop, commpop, male, female, age_0_2, age_3_4, age_5_7, age_8_9, age_10_14, age_15, age_16_17, age_18_19, age_20_24, age_25_29, age_30_34, age_35_39, age_40_44, age_45_49, age_50_54, age_55_59, age_60_64, age_65, age_66_69, age_70_74, age_75_79, age_80_84, age_85_pl, divorced, msnotapply, formciv, civil_os, civil_ss, married_os, married_ss, single, sep_civ, sepmarried, survciv, widowed, aabwbang, aabwchin, aabwindia, aabwoth, aabwpak, bbwcaafr, bbwcacar, bbwcaoth, mixedeth, othereth, whitetot, whitebr, cobafrica, cobanocoth, cobbriosea, cobeuother, cobeu14, cobeu2, cobeu8, cobnoneu, cobuk, cobmea, cobamca, rbuddhist, rchrist, rhindu, rjewish, rmuslim, noreligion, noanswer, otherrel, rsikh, badhealth, fairhealth, ghealth, vbadhealth, vghealth, eaemp, eaeself, eaunemp, eafutist, eiltsdis, eihfam, eioth, eiret, eistu, agricult, extractive, manufact, energysup, ind_dna, watersup, construct, retail, transport, accommfood, infocomms, finserv, propserv, proftech, administ, pubaddef, education, health, otherind, nssecdna, l123hmapro, l1011lstec, l12semrou, l13routine, l14nwltune, l15ftstu, l456lmapro, l7inter, l89seoacc, lq_appren, lq_na, lq_level1, lq_level2, lq_level3, lq_level4, lq_no, lq_other, edu_na, notstudent, student, multoth, multdepkid, pens1pers, other1pers, pensfamily, condepkid, conokid, codepkid, lpndepkid, lpdepkid, mandepkid, madepkid, manokid, singoth, at_mobile, at_detach, at_comm, at_flat, at_anyconv, at_othconv, at_semdet, at_terr, ten_rentfr, ten_ownout, ten_ownmort, ten_proth, ten_prllla, ten_so, ten_sroth, ten_srrent, cva_1, cva_2, cva_3pl, cva_no, pers1hhd, pers2hhd, pers3hhd, pers4hhd, pers5hhd, pers6plhhd, abhrp, c1hrp, c2hrp, dehrp, g.geom
FROM geocrud.geolytix_census_2021
left join
(
 select geoid as code, geom from geocrud.scotland_oa_2022
 union all
 select oa21cd as code, geom from geocrud.england_oa_2021
 union all
 select oa21cd as code, geom from geocrud.wales_oa_2021
) g on (geocrud.geolytix_census_2021.oa_code = g.code)
where geocrud.geolytix_census_2021.oa_code not like 'N%'