INSERT INTO public.censustrips_outputarea
(
 oacode, popx, popy, totpop, totpop01, totadult, tot16to74, totemploy, ttwbasepop, hhdpop, commpop, dwelling, hhdspace, hhdocc, hhdempty, hrp16to64, male, female, age0to4, age5to7, age8to9, age10to14, age15, age16to17, age18to19, age20to24, age25to29, age30to44, age45to59, age60to64, age65to74, age75to84, age85to89, age90plus, single, married, samesex, separated, divorced, widowed, whitetot, whitebr, whiteoth, mixedeth, indian, pakistani, bangladesh, chinese, otherasian, blafrican, blcarib, blother, othereth, cobengland, cobwales, cobscot, cobni, cobroi, coboldeu, cobneweu, cobother, passnone, passuk, passroi, passeu, passnoneu, passafrica, passmea, passnam, passcam, passsam, passocean, catholic, otchrist, totchrist, buddhist, hindu, jewish, muslim, sikh, otrel, tototrel, noreligion, religionns, vghealth, ghealth, fairhealth, badhealth, vbadhealth, eaemppt, eaempft, easelfemp, eaunemp, eafutist, eiretired, eifutist, eihome, eisickdis, eiother, agricult, extractive, manufact, energysup, watersup, construct, retail, transport, accommfood, infocomms, finserv, propserv, proftech, administ, pubaddef, education, health, otherind, empandmgr, highprof, lowprof, intermed, smempseem, lowsuper, semirout, "routine", neverwork, ltunemp, notclass, noquals, qual1, qual2, qualapp, qual3, qual4, qualother, stud16to17, stud18plus, ftsemploy, ftsunemp, ftsecinact, ttwhome, ttwtrain, ttwtube, ttwbus, ttwmbike, ttwcar, ttwcarpass, ttwtaxi, ttwbike, ttwfoot, ttwother, pens1pers, other1pers, pensfamily, manokid, madepkid, mandepkid, conokid, codepkid, condepkid, lpdepkid, lpndepkid, othdepkid, allstudent, otherpens, otherhhd, dwunshared, dwshared, detached, semidetach, terrace, flatpur, flatconsha, commbuild, caravmob, ownout, ownmort, ownshare, soccouncil, socother, privrentl, privrento, rentfree, nocars, car1, car2, car3, car4plus, pers1hhd, pers2hhd, pers3hhd, pers4hhd, pers5hhd, pers6hhd, pers7hhd, pers8phhd, abhrp, c1hrp, c2hrp, dehrp, mpoly)
SELECT oacode, popx, popy, totpop, totpop01, totadult, tot16to74, totemploy, ttwbasepop, hhdpop, commpop, dwelling, hhdspace, hhdocc, hhdempty, hrp16to64, male, female, age0to4, age5to7, age8to9, age10to14, age15, age16to17, age18to19, age20to24, age25to29, age30to44, age45to59, age60to64, age65to74, age75to84, age85to89, age90plus, single, married, samesex, separated, divorced, widowed, whitetot, whitebr, whiteoth, mixedeth, indian, pakistani, bangladesh, chinese, otherasian, blafrican, blcarib, blother, othereth, cobengland, cobwales, cobscot, cobni, cobroi, coboldeu, cobneweu, cobother, passnone, passuk, passroi, passeu, passnoneu, passafrica, passmea, passnam, passcam, passsam, passocean, catholic, otchrist, totchrist, buddhist, hindu, jewish, muslim, sikh, otrel, tototrel, noreligion, religionns, vghealth, ghealth, fairhealth, badhealth, vbadhealth, eaemppt, eaempft, easelfemp, eaunemp, eafutist, eiretired, eifutist, eihome, eisickdis, eiother, agricult, extractive, manufact, energysup, watersup, construct, retail, transport, accommfood, infocomms, finserv, propserv, proftech, administ, pubaddef, education, health, otherind, empandmgr, highprof, lowprof, intermed, smempseem, lowsuper, semirout, "routine", neverwork, ltunemp, notclass, noquals, qual1, qual2, qualapp, qual3, qual4, qualother, stud16to17, stud18plus, ftsemploy, ftsunemp, ftsecinact, ttwhome, ttwtrain, ttwtube, ttwbus, ttwmbike, ttwcar, ttwcarpass, ttwtaxi, ttwbike, ttwfoot, ttwother, pens1pers, other1pers, pensfamily, manokid, madepkid, mandepkid, conokid, codepkid, condepkid, lpdepkid, lpndepkid, othdepkid, allstudent, otherpens, otherhhd, dwunshared, dwshared, detached, semidetach, terrace, flatpur, flatconsha, commbuild, caravmob, ownout, ownmort, ownshare, soccouncil, socother, privrentl, privrento, rentfree, nocars, car1, car2, car3, car4plus, pers1hhd, pers2hhd, pers3hhd, pers4hhd, pers5hhd, pers6hhd, pers7hhd, pers8phhd, abhrp, c1hrp, c2hrp, dehrp,g.geom
FROM geocrud.geolytix_census_2011
left join
(
 select code, geom from geocrud.scotland_oa_2011
 union all
 select code, geom from geocrud.england_oa_2011
 union all
 select code, geom from geocrud.wales_oa_2011
) g on (geocrud.geolytix_census_2011.oacode = g.code)
where geocrud.geolytix_census_2011.oacode not like 'N%'